### ISSUE TITLE
fetch-configlet_v3: script doesn't work yet

### ISSUE THREAD

**Issue by wolf99** [exercism/configlet#109]
```bash
$ ./scripts/fetch-configlet_v3
curl: (22) The requested URL returned error: 404 Not Found
```
Running on Ubuntu 20.04 on WSL.

Added the following echo statements:
```bash
get_url () {
    echo "Getting URL"
    curl "${curlopts[@]}" --header 'Accept: application/vnd.github.v3+json' "$LATEST" |
        grep "\"browser_download_url\": \".*/download/.*/configlet.*${SUFFIX}\"$" |
        cut -d'"' -f4
}

echo "Setting up URL"
URL=$(get_url)
echo "URL is: ${URL}"
```
Output shows:
```bash
$ ./scripts/fetch-configlet_v3
Setting up URL
curl: (22) The requested URL returned error: 404 Not Found
```
This is from master branch

**Comment by ee7** [comment]
This is currently expected. Sorry.

The `fetch-configlet_v3` script will only work after we rename this repo from `canonical-data-syncer` to `configlet-v3` and make the first release. That will happen after the holidays.

If you want a fetch script that downloads the final release of `canonical_data_syncer`, please use the one located [here](https://github.com/exercism/python/blob/master/bin/fetch-canonical_data_syncer).

Let me know if there's anything else I can help with.

**Comment by ee7** [comment]
Resolved.

The script is now named `scripts/fetch-configlet`, and it downloads the latest release of `configlet` in this repo:
https://github.com/exercism/configlet/blob/856bd46b47b49857c5a66c8ba5aea911db94042a/scripts/fetch-configlet#L5

You'll have to download that new version of that script - sorry.

Let me know if there's any other problem.
