### ISSUE TITLE
Rename repo to `configlet`

### ISSUE THREAD

**Issue by ee7** [exercism/configlet#124]
- [X] Refactor `canonical_data_syncer` to have a configlet-like interface with a `sync` subcommand, and update docs (https://github.com/exercism/canonical-data-syncer/commit/674758828891f543ac98051dae3ab277a6c420c9)
- [X] Update the `fetch-configlet` script in this repo to support the repo rename (https://github.com/exercism/canonical-data-syncer/commit/05f3514f2fc3bc8a4ff4ed48c3f82d2b98e3ae1d).
- [X] Improve style and fix bugs in `fetch-configlet` scripts.
- [x] Update `fetch-canonical_data_syncer` scripts in `bash`, `common-lisp`, `perl5`, `python`, `raku`, `rust`, `tcl` and `exercism/github-actions`.
- [x] Update `fetch-canonical_data_syncer` scripts in `dart`, `javascript`, `solidity`, `typescript`, `zig` and `exercism/request-new-language-track`.
- [X] Decide whether to rename to `configlet-v3`, `configlet-v4` (if we want to refer to the `configlet` version rather than the Exercism version) or directly to `configlet`. (We'll go to `configlet`)
- [X] Merge #134
- [x] Merge #72.
- [X] Remove old releases of `canonical_data_syncer` apart from `0.17.0`.
- [X] Rewrite history on the main branch to tidy it up (and inform the people who already forked this repo). This also removes old git tags, which is what we want. **IMPORTANT**: do not delete the `v0.17.0` tag on the remote.
- [x] Create `4.0.0-alpha.1` release (and consider not prefixing with `v`).
- [X] When ready, rename `exercism/configlet` to https://github.com/exercism/v2-configlet
- [X] ~2021-01-29 (Fri): Rename the `exercism/canonical-data-syncer` repo to `configlet-v3` for a few seconds, then straight to `configlet`. The first step is to setup a GitHub redirect from `configlet-v3` to `configlet` - we wrote about our plans to develop first in `configlet-v3`, so people might remember that this redirect is expected to exist.~ Edit: we didn't bother with this.
- [X] (Exploding the v3 monorepo will update the `fetch-configlet` script on every track).
- [X] Rename the `0.17.0` release to include "canonical_data_syncer" in the title. But it's critical that we don't cause the `id` value from the GitHub API response to change until we're happy to break all the `fetch-canonical_data_syncer` scripts.
- [x] Delete the `0.17.0` tag of `canonical_data_syncer`, and its release. It doesn't work with the new structure of track repos anyway.
- [x] Transfer relevant issues from the https://github.com/exercism/v2-configlet repo to this one.
- [x] Consider archiving https://github.com/exercism/v2-configlet
- [x] Remove `fetch-canonical_data_syncer` scripts everywhere (recommend using `configlet sync` instead).
- [ ] Update documentation Exercism-wide to refer to `configlet sync`, not `canonical_data_syncer`

Is there anything else to mention?

**Comment by ErikSchierboom** [comment]
I think this about covers it

**Comment by ErikSchierboom** [comment]
Note: the  `Update the fetch-configlet script on every track.` step will be done by me in the exploding of the v3 monorepo script.

**Comment by ErikSchierboom** [comment]
> Decide whether to rename to configlet-v3, configlet-v4 (if we want to refer to the configlet version rather than the Exercism version) or directly to configlet.

Let's directly rename to `configlet`.

**Comment by ErikSchierboom** [comment]
I think we can close this issue, right @ee7?

**Comment by ee7** [comment]
I like the optimistic box-ticking, but I left the `fetch-canonical_data_syncer` box unchecked for a reason :)

> - [ ] Remove fetch-canonical_data_syncer scripts everywhere

See https://github.com/search?q=org%3Aexercism+syncer&type=code

Don't rely on it being called `fetch-canonical_data_syncer`. The rust track renamed it to `fetch_canonical_data_syncer.sh`

**Comment by ErikSchierboom** [comment]
So many tracks! 😱

**Comment by ee7** [comment]
Important remaining mention of `canonical_data_syncer` that we should remove:
https://github.com/exercism/problem-specifications/blob/4ab6ff38e4f3e96be2160360e30c606e94fdb5b6/README.md#track-test-data-tooling

Unimportant, but a bonus:
- https://github.com/exercism/c/blob/96712c76a5a2330e20e485f6006cff477658df69/.gitignore#L3
- https://github.com/exercism/common-lisp/blob/6c710e3b94ae782de5fb72daa6dece94dbcae23d/.gitignore#L8-L9

With these and the above PRs, I think that gets us to zero `canonical_data_syncer` mentions Exercism-wide.

**Comment by ErikSchierboom** [comment]
@ee7 Done

**Comment by ee7** [comment]
I'll close this issue when all the previously linked PRs are merged.
