### ISSUE TITLE
Only run the tests when a source file has changed

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/configlet#141]
To speed up CI builds, we should only run the `tests` workflow when a source file has changed. This includes:

- Any `.nim` file modification
- Any `.nimble` file modification
- Any `.nims` file modification
- Any `.github/bin/*` file modification
- Any `.github/workflows/tests.yml` file modification

Anything more?

**Comment by ee7** [comment]
I think that's everything right now.

Notes:
- we should include changes in `scripts/*` when we get around to adding a test that they run.
- we should include `README.md` if we ever add a test that it contains the output of `configlet --help`.

But the biggest help would be for the macOS builds to stop taking 5-10 minutes in the early build phase.

Here's the current file list:

```
$ git ls-files
.github/CODEOWNERS
.github/bin/build
.github/bin/create-artifact
.github/bin/linux-install-build-tools
.github/bin/publish-release
.github/dependabot.yml
.github/workflows/build.yml
.github/workflows/shellcheck.yml
.github/workflows/tests.yml
.gitignore
LICENSE
README.md
bin/format
bin/release
config.nims
configlet.nimble
scripts/fetch-configlet
scripts/fetch-configlet.ps1
src/cli.nim
src/configlet.nim
src/lint/lint.nim
src/logger.nim
src/sync/check.nim
src/sync/exercises.nim
src/sync/probspecs.nim
src/sync/sync.nim
src/sync/tracks.nim
src/uuid/uuid.nim
tests/all_tests.nim
tests/config.nims
tests/test_binary.nim
tests/test_probspecs.nim
tests/test_uuid.nim
```

**Comment by ee7** [comment]
With #170 we have instead suppressed builds for branches that only affect Markdown files. See the comments in https://github.com/exercism/configlet/pull/162.

@ErikSchierboom Can we close this issue?

**Comment by ErikSchierboom** [comment]
Yes! Sorry about that.
