### ISSUE TITLE
lint: All Markdown in track definitions should lint properly

### ISSUE THREAD

**Issue by coriolinus** [exercism/configlet#150]
In particular, fragments such as `introdcution.md`, `instructions.md`, and the like, should have no issues reported by [`markdownlint`](https://github.com/markdownlint/markdownlint) or a comparable linter. In particular, that implies these properties:

- All files begin with a level-1 title
- No title has a level more than 1 greater than the previous title

## Why?

- It's easier for file authors to ensure their files are valid if they can run a lint locally
- Ensuring a consistent style makes things faster for everyone
- There's already been [some discussion](https://github.com/exercism/v3/issues/2771#issuecomment-726565294) about what makes a Markdown document valid

## Why not?

- We need to change the site templates, which right now inject their own titles
- We need to batch-update all existing markdown files
- We need to apply a ([pretty trivial](https://github.com/exercism/v3/issues/2771#issuecomment-726730839)) transformation to the markdown files to normalize the headings when they're injected into a larger file

## Even so

In my opinion, the benefits outweigh the drawbacks. We have some temporary pain while we update existing files, but from then on, it becomes easier to work with markdown to ensure that the editing experience is smooth and the rendered content is consistent.

**Comment by iHiD** [comment]
@coriolinus For your first rule, are you happy to change it to
- Any initial title must be level-1 title

Not all documents should have a heading, but if they do, I'm ok with that heading always being a `#`.

**Comment by coriolinus** [comment]
Honestly, my goal is to stop markdownlint from complaining. There are at least two different markdownlint implementations, but they share that rule: [1](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md041) [2](https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md041---first-line-in-file-should-be-a-top-level-header). 

It's not obvious to me which templates don't work properly with a top-level header. What would be an example?

**Comment by iHiD** [comment]
Yeah, so basically every file would need that top level heading removed from it before it's rendered. That already happens in lots of places in the UI, where the docs are used for content but not headings.

Take as an example:
- https://github.com/exercism/website-copy/blob/main/pages/contact.md
- https://exercism.io/contact

The heading on the website is unrelated to the content in the document. In v3 this becomes more acute as things like READMEs are generated from lots of files being pieced together, with various headings conditionally inserted.

---

So a proposal that would work for me is that we say every document must start with `#` but that all `#` will always be removed before being rendered. I could probably get behind that, although it'll potentially mean some cleanup of existing files (but a lot of that is happening anyway with the evolution of exercises in v3)

**Comment by coriolinus** [comment]
So, in the rendered contact page, there is in fact a header directly above the content. I don't know if that's hardcoded right now or what, but long-term, it seems to me that just rendering that header from the markdown file wouldn't cause huge issues. 

Still, I'd rather incremental improvements over all-or-nothing. Would it work for you if the policy were: every document must start with `#`, but that some `#` may be removed pre-rendering? As a practical matter, we could universally trim them at least at first, but this wording of the policy means that we can incrementally move to rendering the headers properly.

**Comment by iHiD** [comment]
> So, in the rendered contact page, there is in fact a header directly above the content. I don't know if that's hardcoded right now or what

It's hardcoded yes. A blog is maybe another good example, where the header is separated from the content by quite a lot of "noise" (e.g. a video) in v3, so it can't be just parsed as the markdown. In that example, 

>  it seems to me that just rendering that header from the markdown file wouldn't cause huge issues.

it probably wouldn't here, but in other places, it wouldn't work.

To be clear, I don't mind stripping the headers out at the website level. I just don't really want different rules for different files, as that gets really complex quickly at the website end. So as long as we have a "global' rule, I'm ok.

---

In parallel to posting here, I've also spent some time bouncing this 1-1 with a few people (easier than doing it in here where it would probably have degraded into people taking "sides").

I can get consensus for:
- All docs start with a level-1 title. This is removed before it gets into the "Exercism" website/CLI/etc. So level-1 headings are there purely there for consumers on GH.
- No title has a level more than 1 greater than the previous title
- Use h2 - h4  for semantic headings. (I don't think we need more than 3 layers of nesting)
- We add this to linting rules in conflglet etc

I think there are three categories of docs that get "used" in Exercism:
1. Problem Specs docs (e.g. description.md)
2. Website Copy docs (e.g. contact.md)
3. Track docs (e.g. TESTS.md)

- 1 can be handled by crowd-sourcing people checking the descriptions. We can put a project together for this and ask people for help. It's a relatively trivial job to do each individual one, so good low-hanging fruit for contributors.
- 2 is trivial - I'll do it.
- 3 is going to be largely addressed by the ensuing chaos of https://github.com/exercism/docs/pull/36 (still WIP - comments welcome) anyway, so we can work it out as part of that.

@coriolinus If you're happy with this, I'll put together a "clean" issue and check no-one majorly objects, and then we can update the docs etc, and Erik can do his thing of script-PRing everything :)

Thanks for raising this :)

**Comment by coriolinus** [comment]
Ok, that works for me. Thanks!

**Comment by iHiD** [comment]
Added here: https://github.com/exercism/docs/pull/38 🙂

**Comment by iHiD** [comment]
@coriolinus, my initial work on this:
- https://github.com/exercism/website-copy/pull/1902
- https://github.com/exercism/problem-specifications/pull/1779

Would also appreciate your opinion on:
- https://github.com/exercism/docs/pull/41

**Comment by ee7** [comment]
@ErikSchierboom are we happy to close this now that we have https://github.com/exercism/configlet/issues/249 and [exercism/docs/building/markdown/markdown.md](https://github.com/exercism/docs/blob/main/building/markdown/markdown.md)?

I haven't checked that all the points raised in this issue are addressed in those places.

**Comment by ErikSchierboom** [comment]
Yes.
