### ISSUE TITLE
lint: Add check that all forks of an exercise use the same name

### ISSUE THREAD

**Issue by SaschaMann** [exercism/configlet#156]
See [Slack](https://exercism-team.slack.com/archives/C016Q9KEQ91/p1604157782076000?thread_ts=1604157274.075400&cid=C016Q9KEQ91), which contains

> SaschaMann wrote:
> Should forks of exercises share the same name across all implementations?

> iHiD wrote:
> Yes

**Comment by ee7** [comment]
We no longer want this, correct?

**Comment by ErikSchierboom** [comment]
Correct
