### ISSUE TITLE
sync: `tests.toml` should contain upper level descriptions of nested tests

### ISSUE THREAD

**Issue by SaschaMann** [exercism/configlet#202]
Canonical data may contain nested tests, e.g.

```json
{
      "description": "isosceles triangle",
      "cases": [
        ...
        {
          "uuid": "840ed5f8-366f-43c5-ac69-8f05e6f10bbb",
          "description": "no sides are equal",
          "property": "isosceles",
          "input": {
            "sides": [2, 3, 4]
          },
          "expected": false
        },
        ...
}
```

In tests.toml, only the inner-most description is currently added to the `description` key. For some exercises, like [triangle](https://github.com/exercism/problem-specifications/blob/main/exercises/triangle/canonical-data.json#L74), this leads to several cases having identical descriptions, which makes `tests.toml` harder to read as a maintainer.

Merging the descriptions of all nesting levels may clear things up. The example above could be translated to

```toml
description = "isosceles triangle → no sides are equal"
```

Note that there may be more than two levels that need to be merged, since nesting is not limited by the canonical-data spec.

Alternatively, there could be a new key `super = "isosceles triangle"` though it's not clear how this would work for tests with more than one nesting level.

**Comment by ErikSchierboom** [comment]
> Merging the descriptions of all nesting levels may clear things up. The example above could be translated to
> > description = "isosceles triangle → no sides are equal"

I really like this suggestion!
