### ISSUE TITLE
Move tests.toml to config?

### ISSUE THREAD

**Issue by wolf99** [exercism/configlet#206]
Currently there are two .meta files required for every exercise for every track: `config.json` and `tests.toml`.
Configlet operates on both of these.

I'm curious as to why these are separate files.

Some of the problems we are seeing arise (e.g. #202, #186/#22, etc)  in `tests` could, at least in part, be resolved by moving the information from `test` to the `config` and doing away with `tests`.

Additionally it personally seems odd to me to have a file for all the configuration of an exercise via a tool but then have another little bit more of configuration in a different file but for the same exercise and for use by the same tool.

Is there a specific reason to keep these two files separate?

**Comment by ErikSchierboom** [comment]
I think the main benefit is that it helps separate concerns. All the information in `.meta/config.json` is there for the website to work with. The `tests.toml` file is there for the tracks themselves, not the website.
