### ISSUE TITLE
fetch-configlet: add to `CODEOWNERS` in every track repo

### ISSUE THREAD

**Issue by ee7** [exercism/configlet#286]
This file probably shouldn't be changed on a per-track level, so adding it to `CODEOWNERS` would help us notice if somebody tries to do that.

We could make something like the below change to the typical `.github/CODEOWNERS` file

```diff
 # Maintainers 
 config/maintainers.json @exercism/maintainers-admin

 # Code owners
 .github/CODEOWNERS      @exercism/maintainers-admin

+# Changes to `fetch-configlet` should be made in the `exercism/configlet` repo
+bin/fetch-configlet     @exercism/maintainers-admin
```

**Comment by ee7** [comment]
Tracks where a PR wasn't created:
- `bash` (script is named `bin/fetch_configlet`, with an underscore)
- `elixir` (script is named `bin/fetch_configlet.sh`, with underscore and extension)
- `j` (missing fetch script entirely)
- `julia` (missing fetch script entirely)
- `php` (missing fetch script entirely)
- `research_experiment_1` (I guess you excluded deliberately)
- `scheme` (script located at `scripts/fetch-configlet`)

**Comment by ErikSchierboom** [comment]
@ee7 PRs have been created for all those repos, except the `research_experiment_1` You can omit that repo from any cross-track scripts you run, as it is not actually a track repo.

**Comment by ee7** [comment]
Looks like we're done now. Closing.

```
$ rg --sort path --hidden --glob 'CODEOWNERS' --files-with-matches --ignore-case 'bin/fetch.+configlet' | wc -l
79
```

https://github.com/search?q=topic%3Aexercism-track+org%3Aexercism&type=Repositories
> 79 repository results

**Comment by ErikSchierboom** [comment]
🥳
