### ISSUE TITLE
add version bumping script

### ISSUE THREAD

**Issue by ee7** [exercism/configlet#376]
I wrote one that suits our workflow better than the current script in the repo. I'll tidy it up and add it sometime.

**Comment by ErikSchierboom** [comment]
@wolf99 I think this issue is about something different, namely a script for configlet itself.

**Comment by ee7** [comment]
Closed by https://github.com/exercism/configlet/commit/89c6cb8cecd9dec70f7c67d6d3bacdf9d9c6af37.
