### ISSUE TITLE
build: pin versions of Nimble packages

### ISSUE THREAD

**Issue by ee7** [exercism/configlet#387]
Our `configlet.nimble` currently contains

https://github.com/exercism/configlet/blob/a7c648f84503bc14a7cb6cfa134076aa28cd5b61/configlet.nimble#L10-L13

showing that, currently, we just use the latest version of the Nimble packages `parsetoml`, `cligen`, and `uuids`. This makes the build less reproducible, and allows buggy/malicious updates to these dependencies to affect configlet.

We're in this situation because, unfortunately, Nimble doesn't fully support pinning a fixed hash. It's possible to write e.g. 
```
requires "parsetoml == 0.6.0"
```
and this is probably an improvement, but nothing stops someone with write access to `parsetoml` from tagging a different commit as `0.6.0`.

Some possible solutions:
1. Use git submodules (or similar).
1. Use `==` for each Nimble dependency in the Nimble file, and then make the tests fail if the installed package is not as expected (to catch the re-tag case).
1. Add an extra build script that clones each package repo and installs a fixed version. Then, the dependency is already satisfied when `nimble build` is run.
1. Wait for Nimble to support lock files - this is hopefully coming in the not-so-distant future (see giant PR: https://github.com/nim-lang/nimble/pull/913/files).

**Comment by ee7** [comment]
> 4. Wait for Nimble to support lock files - this is hopefully coming in the not-so-distant future (see giant PR: https://github.com/nim-lang/nimble/pull/913/files).

This PR was merged, and that change will be in Nim 1.6.0. See https://forum.nim-lang.org/t/8404

**Comment by ErikSchierboom** [comment]
Nice! The first RC has just been released, that's great
