### ISSUE TITLE
lint: `files.example` and `files.exemplar` can use same values

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/configlet#443]
The `files.example` and `files.exemplar` arrays within the track's `config.json` file should be allowed to use the same file names (they'll never overlap on the file system). I've just checked the linting rule and if we add the above exception, I think it works. Note that we should also be making a specific exception for the `D` language track, which has the test and solution files be the same.

See https://github.com/exercism/pharo-smalltalk/pull/516/checks?check_run_id=3929554851#step:4:7

**Comment by Bajger** [comment]
Hi! I'm thinking about fix/workaround for Pharo track: 
```
{
  "example": [
    ".meta/solution/%{pascal_slug}.class.st"
  ],
  "exemplar": [
    ".meta/solution/%{pascal_slug}Exemplar.class.st"
  ]
}
```
I don't know the right purpose of exemplar file (could not find it), but it is rather related to concept exercises in v3. We can name classes like `SomeConceptExemplar.class.st`that would be a convenience for sample code. Configuration file can be changed afterwards, if needed.

**Comment by ErikSchierboom** [comment]
@Bajger I've opened a PR to fix this: https://github.com/exercism/configlet/pull/521 Should be merged sometime this week, so if you can hold out a little bit, this will be fixed soon.

**Comment by Bajger** [comment]
Perfect! Thanks for your insight!

**Comment by ErikSchierboom** [comment]
Closed by https://github.com/exercism/configlet/pull/521
