### ISSUE TITLE
lint: potentially update tags for Solidity

### ISSUE THREAD

**Issue by kotp** [exercism/configlet#454]
See exercism/solidity#61 for the entries that are proposed for `src/lint/track_config.nim` in regard to SolidityLang.

**Comment by ee7** [comment]
Could you please open an issue or pull request in https://github.com/exercism/docs for this?

`configlet lint` just uses the tags defined in that repo's [`building/tracks/config.json.md`](https://github.com/exercism/docs/blob/03600928ca8aa863bc9804d6ef90cd4e13bf939f/building/tracks/config-json.md#tags) file.
