### ISSUE TITLE
info subcommand: unimplemented exercises should exclude officially deprecated issues.

### ISSUE THREAD

**Issue by glennj** [exercism/configlet#473]
I don't think we need every track to explicitly forego exercises that the problem-spec repo has deprecated. 

I suggest the process that generates the list of slugs (whatever generates "prob_specs_slugs.txt"?) excludes problem-specification exercises that have a `.deprecated` file.

* binary/.deprecated
* counter/.deprecated
* hexadecimal/.deprecated
* nucleotide-codons/.deprecated
* octal/.deprecated
* point-mutations/.deprecated
* trinary/.deprecated

**Comment by ee7** [comment]
Agreed - I was planning this. Perhaps also listing separately (or omitting) the unimplemented exercises that lack canonical data. Any opinion on that?

Previously mentioned: https://github.com/exercism/configlet/issues/180#issuecomment-934344148.

(But let's track the idea here, and #180 can track the `info` command in general).

**Comment by glennj** [comment]
> Perhaps also listing separately (or omitting) the unimplemented exercises that lack canonical data. Any opinion on that?

No, not particularly. None of the tracks I'm involved in maintaining use generators from the problem-specs.

**Comment by ErikSchierboom** [comment]
> Perhaps also listing separately (or omitting) the unimplemented exercises that lack canonical data. Any opinion on that?

I think it's useful to list the unimplemented exercises that lack canonical data. There have been some exercises for which creating canonical data has been rather hard. They still are valid exercises to implement though. Maybe just list in the regular list but with a suffix like `(missing canonical data)` or something like that?
