### ISSUE TITLE
`generate` option not explained

### ISSUE THREAD

**Issue by wolf99** [exercism/configlet#475]
The `generate` command isn't explained in the help information.

It doesn't appear to take an argument to indicate the exercise to update.

```console
$ configlet generate complex-numbers
Error: invalid argument for command 'generate': 'complex-numbers'

Usage:
  configlet [global-options] <command> [command-options]

Commands:
  lint, sync, uuid, generate, info

Options for sync:
  -e, --exercise <slug>        Only sync this exercise
  -m, --mode <mode>            What to do with missing test cases. Allowed values: c[hoose], i[nclude], e[xclude]
  -p, --prob-specs-dir <dir>   Use this `problem-specifications` directory, rather than cloning temporarily
  -o, --offline                Do not check that the directory specified by `-p, --prob-specs-dir` is up-to-date
  -u, --update                 Prompt the user to include, exclude, or skip any missing tests

Options for uuid:
  -n, --num <int>              Number of UUIDs to generate

Global options:
  -h, --help                   Show this help message and exit
      --version                Show this tool's version information and exit
  -t, --track-dir <dir>        Specify a track directory to use instead of the current directory
  -v, --verbosity <verbosity>  The verbosity of output. Allowed values: q[uiet], n[ormal], d[etailed]
```

Without an option or argument it doesn't appear to do anything. 
Maybe the exercise is already up to date or maybe the command is not implemented 🤷 

```console
$ ./bin/configlet generate

# (no output)
```

This is with the latest version that `fetch-configlet` fetches

```console
$configlet --version
4.0.0-alpha.34
```

Perhaps #366 is intended to resolve this, but I am not sure.

**Comment by ee7** [comment]
Sorry for the confusion. The `configlet --help` message could indeed be much more helpful. I've been working on improving it, though; it'll soon look something like [this](https://github.com/exercism/configlet/blob/2f3c48d3dfddcc5cd4627e66f14d9dfe19d0a017/README.md#usage).

In the future we'll probably have longer command descriptions in the help message, and likely support e.g. `configlet generate --help` for command-specific help. But for now, please see the repo README [here](https://github.com/exercism/configlet#configlet-generate). 

The `generate` command in the current configlet doesn't do the same thing as the old `generate` command in the configlet for Exercism v2. The new `generate` doesn't have anything to do with `problem-specifications`. `sync` is the command that deals with updating from `problem-specifications`.

The usage message is correct that `generate` doesn't currently take an argument or options. But we'll probably try to make its interface consistent with `sync` and `fmt`.

**Comment by wolf99** [comment]
Does the `sync` command currently cover the practice exercise instructions?
Or is there no way to sync those yet?

**Comment by ee7** [comment]
> Does the `sync` command currently cover the practice exercise instructions? Or is there no way to sync those yet?

That's coming in the next release - very soon. The last blocker was resolved yesterday.

In configlet `4.0.0-alpha.34`, `sync` operates only on tests. In `4.0.0-alpha.35`, it will work like [this]( https://github.com/exercism/configlet/blob/2f3c48d3dfddcc5cd4627e66f14d9dfe19d0a017/README.md#configlet-sync).

If you want to update only the docs for the complex-numbers exercise, it'll be:
```
$ configlet sync --docs --update --exercise complex-numbers
```

or in non-interactive, keystroke-saving form:

```
$ configlet sync --docs -uy -e complex-numbers
```

I'll let you know when it's released. Sorry for the delay.

**Comment by wolf99** [comment]
Yay! That's cool 😎
 
Well done @ee7  👍

**Comment by ee7** [comment]
@wolf99 it's now released - see https://github.com/exercism/configlet/releases/tag/4.0.0-alpha.35

The updates to the configlet docs can now be seen in the repo's `README.md`.
