### ISSUE TITLE
build: consider adding e.g. `-march=x86-64-v3`

### ISSUE THREAD

**Issue by ee7** [exercism/configlet#646]
The `-march` and `-mtune` C compiler switches can produce significant speedups for some workloads, and some widely used Linux distributions are in the process of raising the minimum supported microarchitecture level (e.g. by compiling their packages with e.g. `-march=x86-64-v3`).

However, I am against this for configlet because:

- The speedup is a tiny (especially if it's just `x86-64-v2`), and unimportant.
- Simply raising the minimum supported microarchitecture level means that some users with an older `x86-64` processor won't be able to run the configlet release binary.
- It's not worth the complexity or confusion to add an additional, more optimized release asset.

Background, and discussions in Linux distro communities:

- https://en.wikipedia.org/wiki/X86-64#Microarchitecture_levels
- https://gitlab.archlinux.org/archlinux/rfcs/-/blob/master/rfcs/0002-march.rst
- https://gitlab.archlinux.org/archlinux/rfcs/-/merge_requests/0002
- https://www.phoronix.com/scan.php?page=news_item&px=Arch-Linux-x86-64-v3-Port-RFC
- https://www.phoronix.com/scan.php?page=news_item&px=SUSE-ALP-x86-64-Raising-Base
- https://www.phoronix.com/scan.php?page=news_item&px=RHEL-9-x86-64-v2-Plans
- https://sourceware.org/pipermail/libc-alpha/2020-July/116135.html

Some posts from Lemire:

- https://lemire.me/blog/2022/05/25/parsing-json-faster-with-intel-avx-512/
- https://lemire.me/blog/2022/04/28/removing-characters-from-strings-faster-with-avx-512/
- https://lemire.me/blog/2018/07/25/it-is-more-complicated-than-i-thought-mtune-march-in-gcc/

For Arch Linux machines [for the last half of 2021](https://gitlab.archlinux.org/archlinux/rfcs/-/merge_requests/0002#note_55569):

- 7% support only `x86-64`.
- 28% support only up to `x86-64-v2`.
- 62% support only up to `x86-64-v3`
- 3% support up to `x86-64-v4`

As of GCC 12.1.1 (2022-07-30):

```text
valid arguments to ‘-march=’ switch are:
nocona core2 nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell
core-avx2 broadwell skylake skylake-avx512 cannonlake icelake-client rocketlake
icelake-server cascadelake tigerlake cooperlake sapphirerapids alderlake bonnell atom
silvermont slm goldmont goldmont-plus tremont knl knm x86-64 x86-64-v2 x86-64-v3 x86-64-v4
eden-x2 nano nano-1000 nano-2000 nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron
opteron-sse3 athlon64 athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3
bdver4 znver1 znver2 znver3 btver1 btver2 native
```

```text
valid arguments to ‘-mtune=’ switch are:
nocona core2 nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell
core-avx2 broadwell skylake skylake-avx512 cannonlake icelake-client rocketlake
icelake-server cascadelake tigerlake cooperlake sapphirerapids alderlake bonnell atom
silvermont slm goldmont goldmont-plus tremont knl knm intel x86-64 eden-x2 nano nano-1000
nano-2000 nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64
athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4 znver1 znver2
znver3 btver1 btver2 generic native
```

One way to determine the features your CPU supports:

```console
$ /lib/ld-linux-x86-64.so.2 --help
[...]

Subdirectories of glibc-hwcaps directories, in priority order:
  x86-64-v4
  x86-64-v3 (supported, searched)
  x86-64-v2 (supported, searched)

[...]
```

**Comment by ErikSchierboom** [comment]
Thanks for the write-up! Just for the record: I completely agree with the above reasoning.
