### ISSUE TITLE
Generate: slugs with numbers break generation

### ISSUE THREAD

**Issue by jiegillet** [exercism/configlet#663]
Hi!
I was trying to do the equivalent of [this PR](https://github.com/exercism/elixir/pull/1151) in the Elm track, but I ran into an issue.
We have concepts named `basics-1` and `basics-2`, which makes `configlet generate` break.

For the concept exercise `lucians-luscious-lasagna`, I wrote the `introduction.md.tpl` as

```
# Introduction

%{concept: basics-1}
```

But after generation the `introduction.md` is

```
# Introduction

1}
```

The culprit probably is
https://github.com/exercism/configlet/blob/d31e569714c1562eeca76004d5b49d3500ddfc5d/src/generate/generate.nim#L100-L102

It seems that it would be easy enough to support numbers, is that an option?

**Comment by ee7** [comment]
Good catch - thanks.

> It seems that it would be easy enough to support numbers, is that an option?

Yes, I believe we should do this. 

In `lint.md` we specify that:

> The `"concepts[].slug"` value must be a kebab-case string² with length <= 255

and that a [kebab-case string can contain digits](https://github.com/exercism/docs/blob/ba3eba34d3343693785122742c29c1bbd33b2991/building/configlet/lint.md#glossary):

> kebab-case string: a string that contains only characters in the range `[a-z0-9]`, optionally separated by dashes (e.g. "`two-fer`"). It must match the regular expression: `^[a-z0-9]+(-[a-z0-9]+)*$`

So `configlet generate` should support a concept slug that contains a digit in the placeholder.
