### ISSUE TITLE
Don't fail when average run time is an integer

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/configlet#734]
We currently raise an error if the `test_runner.average_run_time` field  is not using decimals. 
However, this should be accepted as it is perfectly fine for the website to use an integer value (and a run time doesn't really benefit much from using decimals anyway).

**Comment by ee7** [comment]
The spec currently [says](https://github.com/exercism/docs/blob/6a0731ff768ff97db524dfbaaadb73a99a754a18/building/configlet/lint.md#rule-configjson-file-is-valid):

> The `"test_runner.average_run_time"` value must be a floating-point number > 0 with one decimal point of precision

Can we change it there first? If so, do we want it to be:

1. a positive integer
2. a positive integer or a floating-point number > 0 with one decimal point of precision
3. or something else?

**Comment by ErikSchierboom** [comment]
Yes we should change it there! I don't mind people using floating point numbers, as long it is greater than zero. Same with integers

**Comment by ErikSchierboom** [comment]
https://github.com/exercism/docs/pull/430

**Comment by ee7** [comment]
Closed by https://github.com/exercism/configlet/commit/d2e04a5f7ed187f50374bd89c3cc16eef40c3d0d
