### ISSUE TITLE
fetch-configlet.ps1: fails in CI

### ISSUE THREAD

**Issue by ee7** [exercism/configlet#786]
Unless this is some transient error, it looks like the fetch-configlet PowerShell script now [fails in CI](https://github.com/exercism/configlet/actions/runs/5848264601/job/15855487178):

```text
Invoke-WebRequest: D:\a\configlet\configlet\scripts\fetch-configlet.ps1:29
Line |
  29 |  Invoke-WebRequest -Uri $downloadUrl -OutFile $outputFile @requestOpts
     |                         ~~~~~~~~~~~~
     | Cannot convert 'System.Object[]' to the type 'System.Uri' required by parameter 'Uri'. Specified method is not
     | supported.

Error: Process completed with exit code 1.
```

The workflow pins the version of Windows:

https://github.com/exercism/configlet/blob/5e6ddd83d70d1b395d3405dd14d00d3ad3fad4ea/.github/workflows/fetch-configlet.yml#L25

but does not pin the version of PowerShell.

The job was [successful](https://github.com/exercism/configlet/actions/runs/5807860621/job/15743606753) with image version [20230730.1](https://github.com/actions/runner-images/releases/tag/win22%2F20230730.1) but fails with image version [20230804.1.1](https://github.com/actions/runner-images/releases/tag/win22%2F20230804.1)

**Comment by ErikSchierboom** [comment]
Fixed in https://github.com/exercism/configlet/pull/787
