### ISSUE TITLE
helpers, etc: consider exporting jsony

### ISSUE THREAD

**Issue by ee7** [exercism/configlet#817]
Follow up from https://github.com/exercism/configlet/pull/770#issuecomment-1719144745

**Comment by ee7** [comment]
@ErikSchierboom Any idea why the bot closed this? Did something change recently with the pause-community-contributions workflow or its detection of org members? It's never before closed an issue that I created.

The workflow run: https://github.com/exercism/configlet/actions/runs/6183940621/job/16786665696

**Comment by ErikSchierboom** [comment]
I think it is most likely the API call that failed

**Comment by ee7** [comment]
Fair enough.
