### ISSUE TITLE
lint: should allow omitting keys: `concepts` and `exercises.concept`

### ISSUE THREAD

**Issue by ee7** [exercism/configlet#831]
Due to https://github.com/exercism/configlet/commit/66914845a323d2e21ab7d8b00b7219d0777f4c17, `fmt` removes these key/value pairs when the values are empty. But that causes `lint` to produce an error.

This behavior was included in 4.0.0-beta.15, which was available for a little less than an hour. But I rolled back (by marking it as a prerelease), so `fetch-configlet` once again downloads the previous version.

To-do:

- [x] Either:
   - make `lint` allow these keys to be missing
   - or make `fmt` not remove these key/value pairs when the value is empty.
- [ ] Ideally, add some new integration tests, where we run `configlet lint` after `configlet fmt` makes changes to track-level `config.json` files
- [ ] Release 4.0.0-beta.16.

Reported by: https://forum.exercism.org/t/configlet-woes-fmt-removed-too-much/7605

@ErikSchierboom what would you prefer here? To change the behavior of `lint` (and the spec), or change the behavior of `fmt`?

The lint spec currently says that the keys are required:

- https://github.com/exercism/docs/blob/839596f45ecd8e258bbf1f76a12ac46b20facbe7/building/configlet/lint.md?plain=1#L115
- https://github.com/exercism/docs/blob/839596f45ecd8e258bbf1f76a12ac46b20facbe7/building/configlet/lint.md?plain=1#L179

**Comment by ErikSchierboom** [comment]
> @ErikSchierboom what would you prefer here? To change the behavior of lint (and the spec), or change the behavior of fmt?

I would prefer changing `lint` and the spec. It is perfectly fine for tracks to not have concepts or concept exercises I feel, and there is little value in them being empty arrays.

**Comment by ErikSchierboom** [comment]
And in practice they _are_ optional, as we gracefully handle them not being there.

**Comment by ErikSchierboom** [comment]
> Ideally, add some new integration tests, where we run configlet lint after configlet fmt makes changes to track-level config.json files

That's a great idea.

**Comment by ee7** [comment]
> I would prefer changing `lint` and the spec. It is perfectly fine for tracks to not have concepts or concept exercises I feel, and there is little value in them being empty arrays.

OK. Let's go with that. Maybe later we could also check there aren't any other keys that are currently required, but could be optional.
