### ISSUE TITLE
Configlet being detected as a threat by windows defender

### ISSUE THREAD

**Issue by manumafe98** [exercism/configlet#848]
Hi! I've been collaborating in the ``Java Exercism Track`` and recently when I use configlet I'm getting a message from windows defender that is detecting the execution as a threat. [More info](https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3AWin64%2FCobaltStrike.HP!MTB&threatid=2147897830)

Current version installed: ``4.0.0-beta.16``

**Comment by ee7** [comment]
Hi. I can assure you that this is a false positive. Configlet is not malware.

Unfortunately, it is a well-known and long-running issue that antivirus software too-often incorrectly flag Nim executables (like configlet) as a virus. It happens even for the main Nim installer or compiler itself. Sadly, there isn't much that we can do about it.

Sorry that you've encountered this - it's the first time I've heard about somebody encountering this for configlet.

Some discussion elsewhere:

- https://forum.nim-lang.org/t/9358
- [nim-lang/Nim#17820](https://www.github.com/nim-lang/Nim/issues/17820)
- https://forum.nim-lang.org/t/7885
- https://forum.nim-lang.org/t/9388
- https://forum.nim-lang.org/t/9744
- https://forum.nim-lang.org/t/10824
- https://news.ycombinator.com/item?id=30586368
- https://news.ycombinator.com/item?id=29938529
- https://news.ycombinator.com/item?id=32615536
- https://news.ycombinator.com/item?id=34849327
